apiVersion: v1
kind: Service
metadata:
  name: cctest
  namespace: cctest
  labels:
    app.kubernetes.io/name: cctest
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: cctest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000