apiVersion: v1
kind: Service
metadata:
    name: "proxynorbaccluster2-f981"
    labels:
        app: "proxynorbaccluster2-f981"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "proxynorbaccluster2-f981"